name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node and npm
        uses: actions/setup-node@v4
        with:
          node-version: ^20.17.0
          cache: npm

      - name: Install Node dependencies
        run: npm install

      - name: Run Build Test
        run: npm run build
